GETAF/Controllers/AlterarSenhaController.cs
using GETAF.Helper;
using GETAF.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace GETAF.Controllers
{
    public class AlterarSenhaController : Controller
    {

        private readonly ISessao _sessao;
        public AlterarSenhaController(ISessao sessao)
        {
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RedefinirSenha([FromBody] AlterarSenhaModel alterarSenhaModel)
        {
            string email;

            var usuario = _sessao.BuscarSessaoUsuario("SessaoUsuarioLogado");

            if(usuario != null)
            {
                email = usuario.Email;
                var resposta = alterarSenhaModel.RedefinirSenha(email);

                _sessao.RemoverSessaoUsuario("SessaoUsuarioLogado");
                return Json(new { sucesso = resposta.Sucesso, mensagem = resposta.Mensagem });
            }
            else
            {
                email = TempData["EmailUsuario"] as string;
                var resposta = alterarSenhaModel.RedefinirSenha(email);

                return Json(new { sucesso = resposta.Sucesso, mensagem = resposta.Mensagem });
            }
        }
    }
}

GETAF/Controllers/ConfiguracaoController.cs
using GETAF.Helper;
using GETAF.Models;
using GETAF.Models.Context;
using GETAF.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GETAF.Controllers
{
    public class ConfiguracaoController : Controller
    {
        private readonly string _caminhoImagens;
        private readonly ISessao _sessao;
        public ConfiguracaoController(ISessao sessao, IWebHostEnvironment ambiente)
        {
            _sessao = sessao;
            _caminhoImagens = Path.Combine(ambiente.WebRootPath, "Imagens");
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DeletarConta()
        {
            return View();
        }

        public JsonResult EditarNome([FromBody] ConfiguracaoModel config)
        {
            var usuario = _sessao.BuscarSessaoUsuario("SessaoUsuarioLogado");
            var resposta = config.EditarNome(usuario);

            if (resposta.Sucesso)
                _sessao.AtualizarSessaoUsuario("SessaoUsuarioLogado");

            return Json(new { sucesso = resposta.Sucesso, mensagem = resposta.Mensagem });
        }

        public JsonResult DeletarContaUsuario()
        {
            var config = new ConfiguracaoModel();
            var usuario = _sessao.BuscarSessaoUsuario("SessaoUsuarioLogado");
            var resposta = config.DeletarContaUsuario(usuario);

            if (resposta.Sucesso) {
                _sessao.RemoverSessaoUsuario("SessaoUsuarioLogado");
            }

            return Json(new { sucesso = resposta.Sucesso, mensagem = resposta.Mensagem });
        }

        [HttpPost]
        public async Task<IActionResult> UploadImagem(IFormFile foto) {
            if (foto == null || foto.Length == 0)
            {
                return Json(new { sucesso = false, mensagem = "Nenhuma imagem foi enviada." });
            }
            if (!Directory.Exists(_caminhoImagens))
            {
                Directory.CreateDirectory(_caminhoImagens);
            }
            using (var memoryStream = new MemoryStream())
            {
                await foto.CopyToAsync(memoryStream);
                var fotoBytes = memoryStream.ToArray();
                var usuario = _sessao.BuscarSessaoUsuario("SessaoUsuarioLogado");
                usuario.Foto = fotoBytes;
                using (var context = new AppDbContext())
                {
                    context.Usuarios.Update(usuario);
                    await context.SaveChangesAsync();
                }
                _sessao.AtualizarSessaoUsuario("SessaoUsuarioLogado");
                return Json(new { sucesso = true, mensagem = "Imagem carregada com sucesso!" });
            }
        }
        public IActionResult GetUserImage()
        {
            var usuario = _sessao.BuscarSessaoUsuario("SessaoUsuarioLogado");
            if (usuario != null && usuario.Foto != null)
            {
                return File(usuario.Foto, "image/png"); // Retorne no tipo de imagem correta
            }

            return File("/Imagens/default.png", "image/png"); // Imagem padrão se o usuário não tiver uma imagem
        }
    }
}

GETAF/Controllers/LoginController.cs
using GETAF.Helper;
using GETAF.Models;
using GETAF.Models.Context;
using GETAF.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GETAF.Controllers {
    public class LoginController : Controller {

        private readonly ISessao _sessao;
        public LoginController(ISessao sessao)
        {
            _sessao = sessao;
        }
         
        public IActionResult Index() {

            _sessao.RemoverSessaoUsuario("SessaoUsuarioLogado");
            return View();
        }

        public IActionResult ValidarLogin([FromBody] LoginModel login)
        {
            var (usuario, resposta) = login.ValidarLogin();
            
            if(resposta.Sucesso)
            {
                _sessao.CriarSessaoUsuario("SessaoUsuarioLogado", usuario);
                return Json(new { sucesso = true });
            }
            return Json(new { sucesso = false, mensagem = resposta.Mensagem });
        }
    }
}

GETAF/Views/Configuracao/DeletarConta.cshtml
@{
    Layout = "_LayoutTopMenu";
}
<link rel="stylesheet" href="/css/Configuracao/DeletarConta.css">

<div class="content">
    <h2>Configurações</h2>
        <div class="delete-account">
            <h3>Deletar conta</h3>
            <p class="p"><span class="material-symbols-outlined info-icon">info</span> Esta ação é irreversível.</p>
            <div class="user-icon">
            <img src="@Url.Action("GetUserImage", "Configuracao")" alt="Foto de perfil" class="avatar" id="avatarImg">
            </div>
            <p class="confirmation-text">Você tem certeza que deseja excluir sua conta?</p>
            <div class="actions">
                <button class="cancel-btn" onclick="Cancelar()">Cancelar</button>
                <button class="delete-btn" onclick="DeletarContaUsuario()">Deletar conta</button>
            </div>
        </div>
</div>

<script>

    function Cancelar() {
            window.location.href = '@Url.Action("Index", "Configuracao")';
        }

    function DeletarContaUsuario() {
            
        $.ajax({
                url: '@Url.Action("DeletarContaUsuario", "Configuracao")',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                type: "POST",
                success: function (retorno) {
                    if (retorno.sucesso) {
                        window.location.href = '@Url.Action("Index", "Login")';
                    }
                    else
                    {
                        alert('Não foi possível alterar o nome. ' + retorno.mensagem);
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                         console.error(jqXHR.responseText);
                    alert('Algo deu errado ao fazer o login: ' + textStatus);
                }
            });
        }
        
</script>

GETAF/Views/Configuracao/Index.cshtml
@{
    Layout = "_LayoutTopMenu";
}


<link rel="stylesheet" href="/css/Configuracao/Index.css">

<div class="content">
    <h2 class="config">Configurações</h2>
    <div class="profile-box">
        <div class="profile-header">
            <label for="fotoPerfil" style="cursor: pointer;">
                <img src="@Url.Action("GetUserImage", "Configuracao")" alt="Foto de perfil" class="avatar" id="avatarImg">
                <span class="material-symbols-outlined camera-icon">photo_camera</span>
            </label>
            <input type="file" id="fotoPerfil" name="foto" style="display: none;" onchange="UploadImagem();" />

            <div id="edit">
                <h2>Editar perfil</h2>
                <p>Altere os campos abaixo para editar seu perfil.</p>
            </div>

        </div>
        <form action="#"><!--enctype="multipart/form-data" method="post"-->
            <section id="sec-nome">
                <input type="text" id="nome" placeholder="Nome">
            </section>
            <div class="button-group">
                <button type="button" class="cancel-btn">Cancelar</button>
                <button type="submit" onclick="EditarNome()" class="confirm-btn">Confirmar</button>
            </div>
            <a href="#" class="change-password" onclick="AlterarSenha()">Alterar Senha</a>
            <a href="#" class="delete-account" onclick="DeletarConta()">Deletar conta</a>
        </form>
    </div>
</div>

 
    <script>

        function EditarNome() {
            var nome = document.getElementById('nome');
            if (nome.value.length == 0) {
                alert('O nome não foi escrito!');
                nome.focus();
                return;
            }

            $.ajax({
                url: '@Url.Action("EditarNome", "Configuracao")',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                type: "POST",
                data: JSON.stringify({
                    Nome: nome.value
                }),
                success: function (retorno) {
                    if (retorno.sucesso) {
                        window.location.href = '@Url.Action("Index", "Home")';
                    }
                    else
                    {
                        alert('Não foi possível alterar o nome. ' + retorno.mensagem);
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.error(jqXHR.responseText);
                    alert('Algo deu errado ao fazer o login: ' + textStatus);
                }
            });
        }

        function UploadImagem() {
            var input = document.getElementById("fotoPerfil");

            if (input.files.length === 0) {
                alert("Nenhum arquivo selecionado.");
                return;
            }

            var formData = new FormData();
            formData.append("foto", input.files[0]);
            fetch('/Configuracao/UploadImagem', {
                method: 'POST',
                body: formData
            })
                .then(response => response.json())
                .then(data => {
                    if (data.sucesso) {
                        // Atualiza a imagem de perfil no layout
                        const avatarImg = document.getElementById("avatarImg");
                        avatarImg.src = "";
                        setTimeout(() => {
                            avatarImg.src = '/Configuracao/GetUserImage?' + new Date().getTime();
                        atualizarImagemPerfil('/Configuracao/GetUserImage?' + new Date().getTime());
                        }, 100);
                    } else {
                        alert("Falha ao atualizar a imagem: " + data.mensagem);
                    }
                })
                .catch(error => console.error("Erro:", error));

    }

        function AlterarSenha() {
            window.location.href = '@Url.Action("Index", "AlterarSenha")';
        }

        function DeletarConta() {
            window.location.href = '@Url.Action("DeletarConta", "Configuracao")';
        }
    </script>