GETAF/Controllers/AlterarSenhaController.cs
using GETAF.Helper;
using GETAF.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace GETAF.Controllers
{
    public class AlterarSenhaController : Controller
    {

        private readonly ISessao _sessao;
        public AlterarSenhaController(ISessao sessao)
        {
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RedefinirSenha([FromBody] AlterarSenhaModel alterarSenhaModel)
        {
            string email;

            var usuario = _sessao.BuscarSessaoUsuario("SessaoUsuarioLogado");

            if(usuario != null)
            {
                email = usuario.Email;
                var resposta = alterarSenhaModel.RedefinirSenha(email);

                _sessao.RemoverSessaoUsuario("SessaoUsuarioLogado");
                return Json(new { sucesso = resposta.Sucesso, mensagem = resposta.Mensagem });
            }
            else
            {
                email = TempData["EmailUsuario"] as string;
                var resposta = alterarSenhaModel.RedefinirSenha(email);

                return Json(new { sucesso = resposta.Sucesso, mensagem = resposta.Mensagem });
            }
        }
    }
}

GETAF/Controllers/CodigoSenhaController.cs
using GETAF.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GETAF.Controllers
{
    public class CodigoSenhaController : Controller
    {
        public IActionResult Index(string email) {
            ViewBag.Email = email;
            return View();
        }

        public IActionResult VerificarCodigo([FromBody] CodigoSenhaModel codigoSenhaModel)
        {
            var codigoGerado = HttpContext.Session.GetString("CodigoGerado");
            var resposta = codigoSenhaModel.VerificarCodigo(codigoGerado);

            return Json(new { sucesso = resposta.Sucesso, mensagem = resposta.Mensagem });
        }
    }
}

GETAF/Controllers/EsqueciSenhaController.cs
using GETAF.Helper;
using GETAF.Models;
using GETAF.Models.Context;
using GETAF.Models.Entities;
using GETAF.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Web.Helpers;

namespace GETAF.Controllers
{
    public class EsqueciSenhaController : Controller
    {
        private readonly IEmail _email;
        public string CodigoGerado;

        public EsqueciSenhaController(IEmail email)
        {
            _email = email;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ReceberCodigo([FromBody] EsqueciSenhaModel esqueciSenhaModel)
        {
            var (usuario, resposta) = esqueciSenhaModel.ReceberCodigo();
            var emailCapturado = usuario.Email;

            TempData["EmailUsuario"] = emailCapturado;

            if (resposta.Sucesso)
            {
                CodigoGerado = (Guid.NewGuid().ToString().Substring(0, 8)).ToUpper();
                HttpContext.Session.SetString("CodigoGerado", CodigoGerado);
                bool emailEnviado = await _email.EnviarAsync(usuario.Email, "Código para redefinir senha", $"Seu código para redefinir a senha é: {CodigoGerado}");

                if (emailEnviado)
                {
                    return Json(new { sucesso = resposta.Sucesso && emailEnviado, mensagem = resposta.Mensagem });
                }
            }

            return Json(new { sucesso = resposta.Sucesso, mensagem = resposta.Mensagem });
        }
    }
} 

GETAF/Controllers/LoginController.cs
using GETAF.Helper;
using GETAF.Models;
using GETAF.Models.Context;
using GETAF.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GETAF.Controllers {
    public class LoginController : Controller {

        private readonly ISessao _sessao;
        public LoginController(ISessao sessao)
        {
            _sessao = sessao;
        }
         
        public IActionResult Index() {

            _sessao.RemoverSessaoUsuario("SessaoUsuarioLogado");
            return View();
        }

        public IActionResult ValidarLogin([FromBody] LoginModel login)
        {
            var (usuario, resposta) = login.ValidarLogin();
            
            if(resposta.Sucesso)
            {
                _sessao.CriarSessaoUsuario("SessaoUsuarioLogado", usuario);
                return Json(new { sucesso = true });
            }
            return Json(new { sucesso = false, mensagem = resposta.Mensagem });
        }
    }
}

GETAF/Views/CodigoSenha/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="~/css/CodigoSenha/Index.css">
    <title>Código para redefinir senha</title>
</head>
<body>
    <div class="container">
        <div class="voltar" onclick="window.location.href='./login.html'">
            <span class="material-symbols-outlined">arrow_back_ios</span>
        </div>
        <div class="logo">
            <img src="~/Imagens/logo_icon.png" alt="Logo">
        </div>
        <h2>Esqueci a senha</h2>
        <p>Digite o código para a redefinição de senha.</p>
        <div class="form">
            <input placeholder="Código" id="codigo" required>
        </div>
        <div class="botao-container">
            <button class="confirmar" id="confirmar">Confirmar</button>
        </div>
        <div class="codigo-n">
            <a>Não recebeu um código?</a>
        </div>
    <div class="reenviar">
        <a onclick="ReceberCodigo()">Reenviar</a>
    </div>
    </div>
</body>
</html>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">

    function Voltar() {
        window.location.href = '@Url.Action("Index", "Login")';
    }

    function ReceberCodigo() {
        $.ajax({
            url: '@Url.Action("ReceberCodigo", "EsqueciSenha")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            type: "POST",
            data: JSON.stringify({
                Email: '@ViewBag.Email',
            }),
            success: function (retorno) {
                if (retorno.sucesso) {
                    window.location.href = '@Url.Action("Index", "CodigoSenha")?email=@ViewBag.Email';
                    return;
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.error(jqXHR.responseText);
                alert('Algo deu errado ao fazer o envio: ' + textStatus);
            }
        });
    }

    function VerificarCodigo() {

        var codigo = document.getElementById('codigo');
        if (codigo.value.length == 0) {
            alert('O código não foi escrito');
            codigo.focus();
            return;
        }

        
        $.ajax({
            url: '@Url.Action("VerificarCodigo", "CodigoSenha")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            type: "POST",
            data: JSON.stringify({
                Codigo: codigo.value,
            }),
            success: function (retorno) {
                if (retorno.sucesso) {
                    window.location.href = '@Url.Action("Index", "AlterarSenha")';
                }
                else{
                    alert('Algo deu errado ao fazer o envio: ' + retorno.mensagem);
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.error(jqXHR.responseText);
                alert('Algo deu errado ao fazer o envio: ' + textStatus);
            }
        });
    }

    $(document).ready(function () {
        $('#confirmar').click(function () {
            VerificarCodigo();
        });
    });

</script>