GETAF/Controllers/CadastroController.cs
using GETAF.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GETAF.Controllers
{
    public class CadastroController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }

        public JsonResult Cadastrar([FromBody] CadastroModel cadastro)
        {
            var retorno = cadastro.Cadastrar();
            return Json(retorno);


        }
    }
}

GETAF/Controllers/EsqueciSenhaController.cs
using GETAF.Helper;
using GETAF.Models;
using GETAF.Models.Context;
using GETAF.Models.Entities;
using GETAF.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Web.Helpers;

namespace GETAF.Controllers
{
    public class EsqueciSenhaController : Controller
    {
        private readonly IEmail _email;
        public string CodigoGerado;

        public EsqueciSenhaController(IEmail email)
        {
            _email = email;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ReceberCodigo([FromBody] EsqueciSenhaModel esqueciSenhaModel)
        {
            var (usuario, resposta) = esqueciSenhaModel.ReceberCodigo();
            var emailCapturado = usuario.Email;

            TempData["EmailUsuario"] = emailCapturado;

            if (resposta.Sucesso)
            {
                CodigoGerado = (Guid.NewGuid().ToString().Substring(0, 8)).ToUpper();
                HttpContext.Session.SetString("CodigoGerado", CodigoGerado);
                bool emailEnviado = await _email.EnviarAsync(usuario.Email, "Código para redefinir senha", $"Seu código para redefinir a senha é: {CodigoGerado}");

                if (emailEnviado)
                {
                    return Json(new { sucesso = resposta.Sucesso && emailEnviado, mensagem = resposta.Mensagem });
                }
            }

            return Json(new { sucesso = resposta.Sucesso, mensagem = resposta.Mensagem });
        }
    }
} 

GETAF/Controllers/LoginController.cs
using GETAF.Helper;
using GETAF.Models;
using GETAF.Models.Context;
using GETAF.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GETAF.Controllers {
    public class LoginController : Controller {

        private readonly ISessao _sessao;
        public LoginController(ISessao sessao)
        {
            _sessao = sessao;
        }
         
        public IActionResult Index() {

            _sessao.RemoverSessaoUsuario("SessaoUsuarioLogado");
            return View();
        }

        public IActionResult ValidarLogin([FromBody] LoginModel login)
        {
            var (usuario, resposta) = login.ValidarLogin();
            
            if(resposta.Sucesso)
            {
                _sessao.CriarSessaoUsuario("SessaoUsuarioLogado", usuario);
                return Json(new { sucesso = true });
            }
            return Json(new { sucesso = false, mensagem = resposta.Mensagem });
        }
    }
}

GETAF/Views/Cadastro/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/Cadastro/Index.css">
    <title>UniFocus</title>
</head>
<body>
    <div class="container">
        <div class="pag-esquerda">
            <div class="logo">
                <img src="~/Imagens/logo_icon.png" alt="Logo">
            </div>
            <div class="subtitulo">
                <h2 class="sub-titulo">Tarefas Ágeis</h2>
            </div>
            <div class="slogan">
                Uma forma prática e rápida de gerenciar seus estudos!
            </div>
            <button class="botao" onclick="Entrar()">Entrar</button>
            <div class="esqueci-senha">
                <a href="#" onclick="EsqueciSenha()">Esqueci minha senha</a>
            </div>
        </div>
        <div class="pag-direita">
            <div class="titulo">
                Crie sua conta
            </div>
            <div class="text">
                <p class="texto">Preencha os campos abaixo para criar uma nova conta.</p>
            </div>
            <form>
                <div class="formulario">
                    <label for="name">Digite seu nome completo</label>
                    <input type="text" id="name" name="name" placeholder="Digite o nome completo..." required>
                </div>
                <div class="formulario">
                    <label for="email">E-mail</label>
                    <input type="email" id="email" name="email" placeholder="Digite o e-mail..." required>
                </div>
                <div class="formulario">
                    <label for="password">Senha</label>
                    <input type="password" id="password" name="password" placeholder="Digite a senha..." required>
                </div>
                <div class="formulario">
                    <label for="confirmar-senha">Confirmar senha</label>
                    <input type="password" id="confirmar-senha" name="confirmar-senha" placeholder="Digite a confirmação da senha..." required>
                </div>
                <div class="form">
                    <button onclick="Cadastrar()" type="submit" class="submit">Cadastrar</button>
                </div>

            </form>
        </div>
    </div>
</body>
</html>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    function Cadastrar() {
        event.preventDefault();

        var name = document.getElementById('name');
        if (name.value.length == 0) {
            alert('O Nome não foi escrito!');
            name.focus();
            return;
        }

        var email = document.getElementById('email');
        if (email.value.length == 0) {
            alert('O email não foi escrito!');
            email.focus();
            return;
        }

        var password = document.getElementById('password');
        if (password.value.length == 0) {
            alert('A senha não foi escrita!');
            password.focus();
            return;
        }

        var confirmarsenha = document.getElementById('confirmar-senha');
        if (confirmarsenha.value.length == 0) {
            alert('A confirmação da senha não foi escrita!');
            confirmarsenha.focus();
            return;
        }

        if (password.value != confirmarsenha.value) { 

            alert('As senhas são diferentes');
            password.clear();
            confirmarsenha.clear();
            password.focus();
            return;
        }

        $.ajax({
            url: '@Url.Action("Cadastrar", "Cadastro")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            type: "POST",
            data: JSON.stringify({
                Name: name.value,
                Email: email.value,
                Password: password.value
            }),
            success: function (retorno) {
                if (retorno.sucesso) {
                    alert('Cadastrado com sucesso.');
                    return;
                }
                alert('Não foi possível realizar o cadastro. ' + retorno.mensagem);
            },
            error: function () {
                alert('Algo deu errado ao fazer o cadastro.');
            }
        });
    }

    function EsqueciSenha() {
        window.location.href = '@Url.Action("Index", "EsqueciSenha")';
    }

    function Entrar() {
        window.location.href = '@Url.Action("Index", "Login")';
    }

</script>